version: "3.1"
services:
   springapp:
      image: 456123a/java-web-app-docker:${secret}
      ports:
      - 8080:8080
      networks:
      - springappbridge
      restart: always
   mongocontainer:
      image: mongo
      volumes:
      - mongodb:/data/db
      networks:
      - springappbridge
      restart: always
volumes:
  mongodb:
     driver: local
networks:
  springappbridge:
