version: "3.1"
services:
   springapp:
      image: 456123a/springbootapp:${secret}
      ports:
      - 8080:8080
      networks:
      - springappbridge
      environment:
      - MONGO_DB_HOSTNAME=mongocontainer
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=devdb@1234
      restart: always
   mongocontainer:
      image: mongo
      volumes:
      - mongodb:/data/db
      networks:
      - springappbridge
      environment:
      - MONGO_INITDB_ROOT_USERNAME=devdb
      - MONGO_INITDB_ROOT_PASSWORD=devdb@1234
      restart: always
volumes:
  mongodb:
     driver: local
networks:
  springappbridge:
